### ISSUE TITLE
Datu baseko taulak sortzeko SLQ-ak

### ISSUE THREAD

**Issue by xabikip** [kubbit/gerkud#1]
Kaixo, 
Posible litzateke datu baseak behar dituen oinarrizko taulak sortzeko SQLak igotzea errepositorio honetera?
 SLQ artxibotan bakarrik `TRUNCATE TABLE` aginduak ikusten ditut, eta `CREATE TABLE` egotea interesgarria litzeteke.

Eskerrik asko

**Comment by kubbit** [comment]
Datu basearen egitura sortzeko **config/databases.yml** konfiguratu eta erabili agindu hau:

`php symfony doctrine:build --all --and-load --no-confirmation`

Edo bestela erabili **instalazioa.sh** script-a barne aldagaiak pertsonalizatu ondoren.

**Comment by xabikip** [comment]
Ados, saiatu naiz `php symfony doctrine:build --all --and-load --no-confirmation` agindua exekutatuz baina ondorengo errore mezua ateratzen zait:
` SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes. Failing Query: "CREATE TABLE sf_guard_permission (id BIGINT AUTO_INCREMENT, name VARCHAR(255) NOT NULL UNIQUE, description TEXT, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) ENGINE = INNODB". Failing Query: CREATE TABLE sf_guard_permission (id BIGINT AUTO_INCREMENT, name VARCHAR(255) NOT NULL UNIQUE, description TEXT, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) ENGINE = INNODB `

Irakurri dudanagatik zera izan daiteke `utf8mb4` erabiltzean VARCHAR motako eremuak gehienez 190 karaketere izan dezakete, eta kasu honetan 255 karaketeretakoa sortzen saiatzen da. Ez nago ziur baina 255 defektuz jartzen dio Doctrinek? Badakizu non alda daitekeen hori?
Akats honekin aurkitu zara inoiz, edo jakingo zenuke esaten zer izan daitekeen?

Hemen erreferentzia pare bat:
https://github.com/doctrine/orm/issues/7416
https://github.com/doctrine/dbal/issues/3230

Eskerrik asko

**Comment by kubbit** [comment]
Guk ez dugu inoiz arazo hori izan utf8 (utf8mb3) erabiltzen dugulako. Zenbait aukera daude horren aurrean:
1. **utf8mb3** erabili taula horrentzako (CREATE TABLE aginduaren bukaeran ENGINE=InnoDB DEFAULT CHARSET=utf8 ezarriz).
2. Limitea igo `set global innodb_large_prefix=on;` aginduaren bitartez (innodb_file_format=barracuda izan behar da honetarako).
3. Taulako **name** eremua **VARCHAR(190)** bezala ezarri (agian gerora erroreak izan ditzakezu modu honekin).

`php symfony doctrine:build --all --and-load --no-confirmation` agindua erabili ondoren, fitxategi berri bat sortzen da SQL-ko agindu guztiekin (data/sql/schema.sql). Fitxategi hori aldatu dezakezu eta zuzenean datu basean exekutatu php agindua berriz ere erabili gabe.

**Comment by xabikip** [comment]
Eskerrik asko erantzunagatik.

Zuk esandako lehen aukera erabili dut. `php symfony doctrine:build --all --and-load --no-confirmation` aginduakin sortzen den SQL fitxategian `DEFAULT CHARSET=utf8` gehitu diet taula guztiei eta egoki sortu ditu. Adibide moduan datu batzuk izateko /sql direktorioan dauden sql-ak ere exekutatu ditut, eta egoki joan da.

**Comment by kubbit** [comment]
Primeran!
