### ISSUE TITLE
Euskara hizkuntza lehenetsi bezela

### ISSUE THREAD

**Issue by xabikip** [kubbit/gerkud#3]
Kaixo,
Aplikazioan euskara hizkuntza lehenetsi bezela konfiguratu nahian nabil baina ez du lortzen. Zehazki non konfiguratu behar da hau?
Eskerrik asko.

**Comment by kubbit** [comment]
Gerkud aplikazioak arakatzailetik hartzen du hizkuntza, eta hizkuntza ezezaguna denean Euskera erabiltzen du lehenetsi bezala.

Ez dago hau konfiguratzeko beste modurik, euskeraz agertzea nahi baduzu, konfiguratu arakatzailean webguneak euskeraz ikusteko.

**Comment by xabikip** [comment]
Ados, eskerrik asko azalpenagatik ;)
